import subprocess
import pandas as pd
import single_cell_reloc_parquet.global_functions.global_variables as gv
from pathlib import Path
import os

#, Function for managing the input and output of seperate scipt
def run_r_script(r_script_path, input_df1, input_df2 = None): #* Allow the function to accpet up to two dataframes
    """
    Runs an R script on two input dataframes using the subprocess module.

    Parameters:
        input_df1 (pandas DataFrame): The first input dataframe.
        r_script_path (str): The path to the R script file.

    Returns:
        output_df (pandas DataFrame): The output dataframe generated by the R script.
    """

    #, Convert the input dataframes to R dataframes
    input_r_df1 = "input_df1 <- data.frame(" + input_df2.to_csv(header=False, index=False) + ")"
    if input_r_df2 == None:
        r_cmd = ["Rscript", r_script_path, input_r_df1]
    else:
        input_r_df2 = "input_df2 <- data.frame(" + input_df2.to_csv(header=False, index=False) + ")"
        r_cmd = ["Rscript", r_script_path, input_r_df1, input_r_df2]

    # Run the R script using subprocess and capture the output
    r_output = subprocess.check_output(r_cmd, universal_newlines=True)

    # Convert the R output to a pandas dataframe
    output_df = pd.read_csv(pd.compat.StringIO(r_output), header=None)

    return output_df

if __name__ == "__main__":
    # Run the R script
    GlobalVariables = glv.GlobalVariables()
    file_name = input("Enter the file name: ")
    full_path_file =os.path.join(GlobalVariables.r_script_path, file_name)
    r_script_path = "C:\Users\pcnba\Grant Brown's Lab Dropbox\Peter Bartlett\Peter Bartlett Data\Code\single_cell_reloc\single_cell_reloc_parquet\Visualizations\R_scripts\R_script_1.R"
    output_df = run_r_script(full_path_file)

    # Print the output
    print(output_df)
    output_df.to_parquet("file_name_Red.parquet", index=False) #output the reconverted file from R to a parquet